version: "2.1"

orbs:
  node: circleci/node@5.0.2

executors:
  default:
    docker:
      - image: "cimg/base:stable"

jobs:
  install-node:
    executor: default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
  build:
    executor: default
    steps:
      - run: echo Build

  test:
    executor: default
    steps:
      - run: echo Test

workflows:
  build-and-test:
    jobs:
      - build
      - test:
        requires:
          - build
