version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  deploy-master:
    jobs:
      build:
        working_directory: ~/repo

        steps:
          - checkout
          - run: echo hello world
